syntax = "proto3";

package sf.substreams.rpc.v2;

service Stream {
  rpc Blocks (Request) returns (stream Response);
}

message Request {
  int64 start_block_num = 1;
  string start_cursor = 2;
  uint64 stop_block_num = 3;
  bool final_blocks_only = 4;
  bool production_mode = 5;
  string output_module = 6;
  Modules modules = 7;
}

message Modules {
  repeated Module modules = 1;
  repeated Binary binaries = 2;
}

message Binary {
  string type = 1;
  bytes content = 2;
}

message Module {
  string name = 1;
  oneof kind {
    KindMap kind_map = 2;
    KindStore kind_store = 3;
    KindBlockIndex kind_block_index = 10;
  }
  uint32 binary_index = 4;
  string binary_entrypoint = 5;
  repeated Input inputs = 6;
  Output output = 7;
  uint64 initial_block = 8;
  BlockFilter block_filter = 9;
}

message KindMap {
  string output_type = 1;
}

message KindStore {
  string value_type = 1;
  uint32 update_policy = 2;
  uint32 value_representation = 3;
}

message KindBlockIndex {
  string output_type = 1;
}

message BlockFilter {
  string module = 1;
  string query_string = 2;
}

message Input {
  oneof input {
    Source source = 1;
    Map map = 2;
    Store store = 3;
    Params params = 4;
  }
  message Source { string type = 1; }
  message Map { string module_name = 1; }
  message Store { string module_name = 1; uint32 mode = 2; }
  message Params { string value = 1; }
}

message Output {
  string type = 1;
}

message Response {
  oneof message {
    SessionInit session = 1;
    ModulesProgress progress = 2;
    BlockScopedData block_scoped_data = 3;
    BlockUndoSignal block_undo_signal = 4;
  }
}

message BlockScopedData {
  MapModuleOutput output = 1;
  Clock clock = 2;
  string cursor = 3;
  uint64 final_block_height = 4;
}

message MapModuleOutput {
  string name = 1;
  Any map_output = 2;
}

message Any {
  string type_url = 1;
  bytes value = 2;
}

message Clock {
  string id = 1;
  uint64 number = 2;
}

message BlockRef {
  string id = 1;
  uint64 number = 2;
}

message BlockUndoSignal {
  BlockRef last_valid_block = 1;
  string last_valid_cursor = 2;
}

message SessionInit {}
message ModulesProgress {}
